# Generated by Django 4.2 on 2023-04-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
